apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: blog
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: blog
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: blog
  labels:
    app: php
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: php

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: blog
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx

{{- if .Values.monitor.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: blog
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: blog
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
{{- end }}

{{- if .Values.elasticsearch.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: blog
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: blog
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana

---

apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  namespace: blog
  labels:
    app: fluentd
spec:
  ports:
    - port: 24224
      targetPort: 24224
  selector:
    app: fluentd

